[package]
name = "aoc02b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.23"
tokio = { version = "1.35.1", features = ["full"] }
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
